version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: de-module4-dbt-postgres
    environment:
      POSTGRES_USER: abdou
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: dbt_demo
    ports:
      - "5433:5432"

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.7.latest
    container_name: de-module4-dbt
    depends_on:
      - postgres
    volumes:
      - ./project:/usr/app
    entrypoint: ["tail", "-f", "/dev/null"]
